/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:3d61f802-d585-4c7b-b9cf-8ce9dd20c4ee",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_AcIwtn6v2",
    "aws_user_pools_web_client_id": "37jbo72o1jbass4knem2hs47bg",
    "oauth": {}
};


export default awsmobile;
