/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:3d61f802-d585-4c7b-b9cf-8ce9dd20c4ee",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_AcIwtn6v2",
    "aws_user_pools_web_client_id": "37jbo72o1jbass4knem2hs47bg",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rvau6cuywjawxknkw7e4mdja2u.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h5o2jqmfmjhvbcqbbvjcnhf5au"
};


export default awsmobile;
